platform :ios, '9.0'
inhibit_all_warnings!
target 'SH' do
	pod 'Masonry', '~> 1.1.0'
	pod 'AFNetworking', '~> 3.2.1'
	pod 'SDWebImage', '~> 5.1.0'
	pod 'MJExtension', '~> 3.1.0'
	pod 'CYLTabBarController', '~> 1.28.3'
	pod 'IQKeyboardManager', '~> 6.4.0'
	pod 'YYText', '~> 1.0.7'
	pod 'JXPagingView/Pager'
	pod 'JXCategoryView', '~> 1.5.2'
	pod 'XHLaunchAd', '~> 3.9.8'
	pod 'Somo', '~> 0.8.0'
	pod 'YBImageBrowser', '~> 3.0.6'
        pod 'YBImageBrowser/Video'
	pod 'BRPickerView', '~> 2.4.5'
	pod 'MBProgressHUD', '~> 1.1.0'
	pod 'SGPagingView', '~> 1.6.7'
	pod 'DZNEmptyDataSet', '~> 1.8.1'
	pod 'PPBadgeView', '~> 3.1.0'
#shareSDK
	pod 'mob_sharesdk'
	pod 'mob_sharesdk/ShareSDKUI'
	pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'
end
